###########
# site.url, site.title

url:   'https://scilifelab.github.io/courses'
title: 'SciLifeLab Courses'
google_analytics: 'UA-23985298-11'


########
# more settings

# markdown: kramdown

# pygments: true
highlighter: rouge

sass:
  sass_dir: css
  style:    expanded
  
# enable emojis
gems:
  - jemoji



exclude:
- README.md


safe: true
lsi: false
